src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use App\Entity\Messages;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 * @ORM\Table(name="ticket", indexes={@ORM\Index(columns={"titre_ticket"}, flags={"fulltext"})})
 */
class Ticket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
  

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ticket;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_ticket;

   
    /**
     * @ORM\ManyToOne(targetEntity=CategorieTicket::class, inversedBy="tickets")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=DomainTicket::class, inversedBy="tickets")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Domain;

    /**
     * @ORM\ManyToOne(targetEntity=PrioriteTicket::class, inversedBy="tickets")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Priorite;

    /**
     * @ORM\ManyToOne(targetEntity=SousDomainTicket::class, inversedBy="tickets")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sous_domain;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="tickets")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateurs;

    /**
     * @ORM\OneToMany(targetEntity=UploadFile::class, mappedBy="messages" , cascade={"persist","remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $file;



    /**
     * @ORM\ManyToOne(targetEntity=StatutTicket::class, inversedBy="ticket")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinColumn(nullable=true)
     */
    private $statut_ticket;

 /**
 * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="tickets")
 * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
 */
private $affectation;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="ticketsClient")
     */
    private $Id_client;

    

    /**
     * @ORM\Column(type="text")
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity=ReponseSolway::class, mappedBy="ticket")
     */
    private $reponseSolways;

    /**
     * @ORM\OneToMany(targetEntity=ReponseClient::class, mappedBy="ticket")
     */
    private $reponseClients;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_closed;

   /**
     * @ORM\OneToMany(targetEntity="Messages", mappedBy="ticket", cascade={"persist", "remove"},orphanRemoval=true)

     */
    private $messages;




    /**
     * @ORM\OneToMany(targetEntity=Etat::class, mappedBy="ticket")
     */
    private $etats;


 

    
   

    public function __construct()
    {
        $this->date_ticket = new \Datetime();
        $this->file = new ArrayCollection();
        $this->affectation_id = new ArrayCollection();
        $this->reponseSolways = new ArrayCollection();
        $this->reponseClients = new ArrayCollection();
        $this->etats = new ArrayCollection();
        $this->messages = new ArrayCollection();

     
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateTicket(): ?\DateTimeInterface
    {
        return $this->date_ticket;
    }

    public function setDateTicket(\DateTimeInterface $date_ticket): self
    {
        $this->date_ticket = $date_ticket;

        return $this;
    }

    public function getTitreTicket(): ?string
    {
        return $this->titre_ticket;
    }

    public function setTitreTicket(string $titre_ticket): self
    {
        $this->titre_ticket = $titre_ticket;

        return $this;
    }

   

    public function getCategorie(): ?CategorieTicket
    {
        return $this->categorie;
    }

    public function setCategorie(?CategorieTicket $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDomain(): ?DomainTicket
    {
        return $this->Domain;
    }

    public function setDomain(?DomainTicket $Domain): self
    {
        $this->Domain = $Domain;

        return $this;
    }

    public function getPriorite(): ?PrioriteTicket
    {
        return $this->Priorite;
    }

    public function setPriorite(?PrioriteTicket $Priorite): self
    {
        $this->Priorite = $Priorite;

        return $this;
    }

    public function getSousDomain(): ?SousDomainTicket
    {
        return $this->sous_domain;
    }

    public function setSousDomain(?SousDomainTicket $sous_domain): self
    {
        $this->sous_domain = $sous_domain;

        return $this;
    }

    public function getUtilisateurs(): ?Utilisateurs
    {
        return $this->utilisateurs;
    }

    public function setUtilisateurs(?Utilisateurs $utilisateurs): self
    {
        $this->utilisateurs = $utilisateurs;

        return $this;
    }

    /**
     * @return Collection|UploadFile[]
     */
    public function getFile(): Collection
    {
        return $this->file;
    }

    public function addFile(UploadFile $file): self
    {
        if (!$this->file->contains($file)) {
            $this->file[] = $file;
            $file->setTicket($this);
        }

        return $this;
    }

    public function removeFile(UploadFile $file): self
    {
        if ($this->file->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getTicket() === $this) {
                $file->setTicket(null);
            }
        }

        return $this;
    }


    public function getStatutTicket(): ?StatutTicket
    {
        return $this->statut_ticket;
    }

    public function setStatutTicket(?StatutTicket $statut_ticket): self
    {
        $this->statut_ticket = $statut_ticket;

        return $this;
    }

    public function getAffectation(): ?Utilisateurs
    {
        return $this->affectation;
    }

    public function setAffectation(?Utilisateurs $affectation): self
    {
        $this->affectation = $affectation;

        return $this;
    }

    public function getIdClient(): ?Utilisateurs
    {
        return $this->Id_client;
    }

    public function setIdClient(?Utilisateurs $Id_client): self
    {
        $this->Id_client = $Id_client;

        return $this;
    }


    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection<int, ReponseSolway>
     */
    public function getReponseSolways(): Collection
    {
        return $this->reponseSolways;
    }

    public function addReponseSolway(ReponseSolway $reponseSolway): self
    {
        if (!$this->reponseSolways->contains($reponseSolway)) {
            $this->reponseSolways[] = $reponseSolway;
            $reponseSolway->setTicket($this);
        }

        return $this;
    }

    public function removeReponseSolway(ReponseSolway $reponseSolway): self
    {
        if ($this->reponseSolways->removeElement($reponseSolway)) {
            // set the owning side to null (unless already changed)
            if ($reponseSolway->getTicket() === $this) {
                $reponseSolway->setTicket(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReponseClient>
     */
    public function getReponseClients(): Collection
    {
        return $this->reponseClients;
    }

    public function addReponseClient(ReponseClient $reponseClient): self
    {
        if (!$this->reponseClients->contains($reponseClient)) {
            $this->reponseClients[] = $reponseClient;
            $reponseClient->setTicket($this);
        }

        return $this;
    }

    public function removeReponseClient(ReponseClient $reponseClient): self
    {
        if ($this->reponseClients->removeElement($reponseClient)) {
            // set the owning side to null (unless already changed)
            if ($reponseClient->getTicket() === $this) {
                $reponseClient->setTicket(null);
            }
        }

        return $this;
    }

  


/**
     * Get messages
     *
     * @return Collection<int, Messages>
     */
    public function getMessages()
    {
        return $this->messages;
    }



    public function addMessages(Messages $messages): self
    {
        if (!$this->messages->contains($messages)) {
            $this->messages[] = $messages;
            $messages->setTicket($this);
        }

        return $this;
    }

    public function removeMessages(Messages $messages): self
    {
        if ($this->messages->removeElement($messages)) {
            // set the owning side to null (unless already changed)
            if ($messages->getTicket() === $this) {
                $messages->setTicket(null);
            }
        }

        return $this;
    }
/**
     * @ORM\PreRemove
     */
    public function preRemove()
    {
        foreach ($this->messages as $message) {
            $message->setTicket(null);
        }
    }
    public function isIsClosed(): ?bool
    {
        return $this->is_closed;
    }


templates/Manager/statistique/recherche.html.twig
{% extends 'BaseManager.html.twig' %}

{% block title %}Administration
{% endblock %}

{% block body %}

	<h1 class="mt-5">Statistiques recherche</h1>

	<form class="navbar-form navbar-right" method="post" action="{{ path('admin_ticket') }}">
		<input type="text" class="form-control" placeholder="Search..." name="motcle">
		<table class="table mt-4">
			<thead>
				<tr>
					<th>Id</th>
					<th>Crée par</th>
					<th>crée le</th>
					<th>Titre</th>
					<th>Catégorie</th>
					<th>Domain</th>
					<th>Sous Domain</th>
					<th>priorité</th>
					<th>statut</th>
					<th>responsable</th>
					<th></th>
				</tr>
			</thead>

			<tbody class="tbody">

				{% for ticket in ticket %}
					<tr>
						<th>{{ ticket.getId() }}</th>
						<th>{{ ticket.getUtilisateurs().getEmail() }}</th>
						<th>{{ ticket.getDateTicket()|date("d/m/Y") }}</th>
						<th>{{ ticket.getTitreTicket() }}</th>
						<th>{{ ticket.getCategorie().getNomCategorie() }}</th>
						<th>{{ ticket.getDomain().getNomDomain }}</th>
						<th>{{ ticket.getSousDomain().getNomSsDomain() }}</th>
						<th>{{ ticket.getPriorite().getNiveauPriorite() }}</th>
						<th>{{ ticket.getPriorite().getNiveauPriorite() }}</th>
						<th>{{ ticket.getPriorite().getNiveauPriorite() }}</th>

						<th>
							<div class="div_btn">
								<a href="{{ path('admin_ticket_show', {id: ticket.id}) }}" class="btn btn-info">
									Voir</a>

							</div>
						</th>
					</tr>

				{% else %}
					<tr>
						<th colspan="8">Il n'y a pas de priorité</th>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="pagination">
			{{ knp_pagination_render(ticket) }}
		</div>

	{% endblock %}

templates/Manager/statistique/statistique.html.twig
{% extends 'baseManager.html.twig' %}
{% block title %}{% endblock %}
{% block stylesheets %}



<link rel="stylesheet" href ="{{ asset('css/ticket.css') }}">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css">
 <title>Solway Consulting & Services</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">


 <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22> <text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
          <link rel="stylesheet" href ="{{ asset('css/styles.css') }}">


<style>


.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
    min-width: 1000px;
    background: #fff;
    padding: 20px 25px;
    border-radius: 3px;
    box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
    padding-bottom: 15px;
    background:  #287892;
    color: #fff;
    padding: 16px 30px;
    margin: -20px -25px 10px;
    border-radius: 3px 3px 0 0;
}
.table-title h2 {
    margin: 5px 0 0;
    font-size: 24px;
}
.table-title .btn {
    color: #566787;
    float: right;
    font-size: 13px;
    background: #fff;
    border: none;
    min-width: 50px;
    border-radius: 2px;
    border: none;
    outline: none !important;
    margin-left: 10px;
}
.table-title .btn:hover, .table-title .btn:focus {
    color: #566787;
    background: #f2f2f2;
}
.table-title .btn i {
    float: left;
    font-size: 21px;
    margin-right: 5px;
}
.table-title .btn span {
    float: left;
    margin-top: 2px;
}
table.table tr th, table.table tr td {
    border-color: #e9e9e9;
    padding: 12px 15px;
    vertical-align: middle;
}
table.table tr th:first-child {
    width: 60px;
}
table.table tr th:last-child {
   width: 120px;
}
table.table-striped tbody tr:nth-of-type(odd) {
    background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
    background: #f5f5f5;
}
table.table th i {
    font-size: 13px;
    margin: 0 5px;
    cursor: pointer;
}	
table.table td:last-child i {
    opacity: 0.9;
    font-size: 22px;
    margin: 0 5px;
}
table.table td a {
    font-weight: bold;
    color: #566787;
    display: inline-block;
    text-decoration: none;
}
table.table td a:hover {
    color: #2196F3;
}
table.table td a.settings {
    color: #2196F3;
}
table.table td a.delete {
    color: #F44336;
}
table.table td i {
    font-size: 19px;
}
table.table .avatar {
    border-radius: 50%;
    vertical-align: middle;
    margin-right: 10px;
}
.status {
    font-size: 30px;
    margin: 2px 2px 0 0;
    display: inline-block;
    vertical-align: middle;
    line-height: 10px;
}
.text-success {
    color: #10c469;
}
.text-info {
    color: #62c9e8;
}
.text-warning {
    color: #FFC107;
}
.text-danger {
    color: #ff5b5b;
}
.pagination {
    float: right;
    margin: 0 0 5px;
}
.pagination li a {
    border: none;
    font-size: 13px;
    min-width: 30px;
    min-height: 30px;
    color: #999;
    margin: 0 2px;
    line-height: 30px;
    border-radius: 2px !important;
    text-align: center;
    padding: 0 6px;
}
.pagination li a:hover {
    color: #666;
}	
.pagination li.active a, .pagination li.active a.page-link {
    background: #03A9F4;
}
.pagination li.active a:hover {        
    background: #0397d6;
}
.pagination li.disabled i {
    color: #ccc;
}
.pagination li i {
    font-size: 16px;
    padding-top: 6px
}
.hint-text {
    float: left;
    margin-top: 10px;
    font-size: 13px;
}

</style>

   
{% endblock %}

{% block body %}
<div id="content">
		{{ form_start(form)}}

		

		<div class="row justify-content-around">
			<div class="col-4 mt-2">{{form_row(form.dateDebut)}}</div>

			<div class="col-4 mt-2">{{form_row(form.dateFin)}}</div>


		</div>
		<div class="row row justify-content-around">
			<div class="col-4 mt-2">{{form_row(form.categorie)}}</div>


			<div class="col-4 mt-2">{{form_row(form.Domain)}}</div>


		</div>
		<div class="row row justify-content-around">


			<div class="col-4 mt-2 ">{{form_row(form.sous_domain)}}</div>

			<div class="col-4 mt-2">{{form_row(form.priorite)}}</div>

		</div>
		<div class="row justify-content-around">
			<div class="col-4 mt-2">{{form_row(form.status)}}</div>

			<div class="col-4 mt-2">{{form_row(form.Affectation)}}</div>



		</div>

        	<div class="row justify-content-around">
			<div class="col-4 mt-2">{#{form_row(form.affectation)}#}</div>
            <div class="col-4 mt-2">{#{form_row(form.Affectation)}#}</div>

			



		</div>
        <div class="row justify-content-around">
			<div class="col-4 mt-2"><button type="submit"class="btn btn-ligth" 
            style="background-color: #287892;color:white">Rechercher</div>

			<div class="col-4 mt-2"></div>

		</div>



		{{ form_end(form)}}
   <br><br>
<div class="container-fluid">
 <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2> Résultats de la recherche </b></h2>
                    </div>
                    <div class="col-sm-7">
                        {#{<a href="{{ path('download')}}" class="btn btn-success mt-5">télécharger</a>}#}

                    </div>
                </div>
            </div>
    <table  class="table table-striped table-hover" data-sortable="true" 
    data-filter-control="true"  id="myTable"  style="font-size:17px">
    <div class="loading-text">    </div>
    <thead>
    <tr>

                       <th data-sortable="true" >ID</th>
                        {#{<th >ID createur</th>}#}	
                        {#{<th>Id recepteur </th>}#}				
                        <th data-field="CréePar" data-filter-control="select"
                         data-sortable="true">Crée par</th>
                        <th  data-sortable="true"  >Crée le </th>
                        <th width='50px' data-sortable="true" >Titre</th>
                        <th data-field="Catégorie" data-filter-control="select" data-sortable="true" > Catégorie</th>
                        {#{<th>Domaine</th>}#}
                        <th data-field="SousDomaine" data-filter-control="select" data-sortable="true" >Sous domaine</th>
                        <th data-field="Priorité" data-filter-control="select" data-sortable="true"  >Priorité</th>						
                        <th data-field="Status" data-filter-control="select" data-sortable="true" >Status</th>
                       
                        <th width='500px' >Action</th>
    
    </tr>
    </thead>
    <tbody>
    {% for ticket in ticket %}

         <td>{{ ticket.getId() }}</td>
		<td>{{ ticket.getUtilisateurs().getEmail() }}</td>

		
		<td >{{ ticket.getDateTicket()|date("d/m/Y") }}</td>
		<td  width='200px'> {{ ticket.titreTicket}}</td>
		<td>{{ ticket.getCategorie().getNomCategorie() }}</td>
		<td>{{ ticket.getSousDomain().getNomSsDomain() }}</td>
		<td> {{ ticket.getPriorite().getNiveauPriorite() }} </td>


        {% if ticket.getStatutTicket().getEtatTicket == 'Nouveau' %}

           <td> <span class="badge badge-primary" style="border-radius:20px">
           {{ ticket.getStatutTicket().getEtatTicket() }} </span> </td>


    {% elseif  ticket.getStatutTicket().getEtatTicket == 'en cours' %}

            <td> <span class="badge badge-success" style=" border-radius:20px" >
            {{ ticket.getStatutTicket().getEtatTicket() }} </span> </td>

   {% elseif  ticket.getStatutTicket().getEtatTicket == 'À recetter' %}
               <td> <span class="badge badge-warning" style=" border-radius:20px" >
               {{ ticket.getStatutTicket().getEtatTicket() }} </span> </td>


               {% elseif   ticket.getStatutTicket().getEtatTicket == 'Réouvert' %}
               <td> <span class="badge badge-info" style=" border-radius:20px" >
            {{ ticket.getStatutTicket().getEtatTicket() }} </span> </td>

                {% elseif ticket.getStatutTicket().getEtatTicket == 'Terminé' %}
                  <td> <span class="badge badge-danger" style=" border-radius:20px" >
            {{ ticket.getStatutTicket().getEtatTicket() }} </span> </td>

	  {% endif %}
     






		

                        <td width='150px'>
                        <a href="{{ path('admin_ticket_show', {id: ticket.id}) }}" class="modifier" title="voir" 
                        data-toggle="tooltip">
                        <i class="material-icons" style="color:green">create</i></a>


                        <a href="{{ path('admin_message', {id: ticket.id}) }}" class="settings"
                         title="Messages" data-toggle="tooltip">
                         <i class="fa fa-commenting" aria-hidden="true"></i></a>


                         <a href="#" class="settings" style="color:red" 
                         title="Supprimer" data-toggle="tooltip"><i class="material-icons">delete</i></a>
                        </td>
                    </tr>
                    
               {% endfor %}

    </tbody>
    </table>
</div>

{% block javascripts %}
<script type="text/javascript" src="libs/FileSaver/FileSaver.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
   <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>

 <script src="{{ asset('js/ticket.js') }}"> </script>
 
<script>
$(function() {
    $('#myTable').bootstrapTable()
  })
</script>

<script>
$(document).ready(function () {
$('#myTable').DataTable();
} );

</script>
<script>
$('#myTable').DataTable({
  "language": {
    "sProcessing": "Traitement en cours ...",
    "sLengthMenu": "Afficher _MENU_ lignes",
    "sZeroRecords": "Aucun résultat trouvé",
    "sEmptyTable": "Aucune donnée disponible",
    "sInfo": "Lignes _START_ à _END_ sur _TOTAL_",
    "sInfoEmpty": "Aucune ligne affichée",
    "sInfoFiltered": "(Filtrer un maximum de_MAX_)",
    "sInfoPostFix": "",
    "sSearch": "Chercher:",
    "sUrl": "",
    "sInfoThousands": ",",
    "sLoadingRecords": "Chargement...",
    "oPaginate": {
      "sFirst": "Premier", "sLast": "Dernier", "sNext": "Suivant", "sPrevious": "Précédent"
    },
    "oAria": {
      "sSortAscending": ": Trier par ordre croissant", "sSortDescending": ": Trier par ordre décroissant"
    }
  }
});
</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script><script>
jQuery(document).ready(function () {
$('.js-datepicker').datepicker();
});</script>
{% endblock %}
	{% endblock %}
